In [ ]:
# Numerical Operations

In [1]:
import numpy as np

a = np.array([1,2,3,4,5]);

print(a+1);

[2 3 4 5 6]


In [4]:
print(a**2)

[ 1  4  9 16 25]


In [3]:
print(a-3)

[-2 -1  0  1  2]


In [5]:
print(a/2)

[0.5 1.  1.5 2.  2.5]


In [6]:
a = np.ones((3,3),dtype='int') * 3
print(a)

[[3 3 3]
 [3 3 3]
 [3 3 3]]


In [7]:
b = np.diag([6,2,7])

print(b)

[[6 0 0]
 [0 2 0]
 [0 0 7]]


In [8]:
print(a+b)

[[ 9  3  3]
 [ 3  5  3]
 [ 3  3 10]]


In [9]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

b= np.ones((3,3))+2

In [10]:
print(a*b); #element wise multiplication

[[ 3.  6.  9.]
 [12. 15. 18.]
 [21. 24. 27.]]


In [11]:
a = np.array([1,2,3,4])
b = np.array([1,2,3,6])

a==b

array([ True,  True,  True, False])

In [12]:
a < b

array([False, False, False,  True])

In [13]:
c = np.array([1,2,3,4]);

np.array_equal(a,c)

True

In [ ]:
# Logical Operations

In [14]:
a = np.array([1,0,1,0], dtype='bool')
b = np.array([0,0,1,1], dtype=bool);

np.logical_and(a,b)

array([False, False,  True, False])

In [15]:
np.logical_or(a,b)

array([ True, False,  True,  True])

In [16]:
a = np.arange(4);

np.sin(a)

array([0.        , 0.84147098, 0.90929743, 0.14112001])

In [17]:
np.log(a[2])

0.6931471805599453

In [18]:
np.exp(a)


array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692])

In [ ]:
# Computing Sums

In [19]:
a = np.array([1,2,3,4]);

np.sum(a)

10

In [20]:
x = np.array([[1,2],[3,4]])

print(x);

[[1 2]
 [3 4]]


In [21]:
x.sum(axis=0) #axis 0 implies col

array([4, 6])

In [22]:
x.sum(axis=1) #axis 1 implies row

array([3, 7])

In [23]:
print(x.min());

1


In [24]:
print(x.max());

4


In [25]:
print(x.argmin()); #index of least element

0


In [26]:
print(x.argmax()); #index of larget element

3


In [27]:
#it returns true if all vals are true
np.all([True,True,False])

False

In [28]:
# it returns true if atleaset one val is true

np.any([True,True,False])

True

In [29]:
a = np.zeros((3,3));

np.any(a!=0)

False

In [30]:
np.all(a==0)

True

In [31]:
a= np.array([1,2,3,4])
b= np.array([1,2,3,4])+1
c= np.array([1,2,3,4])+2
((a<b) & (b<c)).all()

True

In [ ]:
# Statistics

In [32]:
x = np.array([1,2,3,4,1,1]);

x.mean()

2.0

In [33]:
np.median(x)

1.5

In [34]:
x.std()

1.1547005383792515

In [ ]:
# Broadcasting
# [ [1,2,3], [1,1,1], [3,2,2] ]

# +

# [ [0,1,2], [0,1,2], [0,1,2] ]

# is same as

# [ [1,2,3], [1,1,1], [3,2,2] ]

# +

# [ [0,1,2], ]

# it will add 2 more rows to sync up with
# first matrix
# Other Example:

# [ [1], [2], [3], [4] ]

# +

# [ [0,1,2] ]

# is same is

# [ [1,2,3,4], [1,2,3,4], [1,2,3,4], [1,2,3,4] ]

# +

# [ [0,1,2], [0,1,2], [0,1,2], [0,1,2] ]



In [36]:
# Tiles

#in 2nd argument 3 is repeat row 3 times and 1
# is repeat col 1 time
a = np.tile(np.arange(3),(3,1))

print(a);

[[0 1 2]
 [0 1 2]
 [0 1 2]]


In [37]:
a = np.tile(np.arange(3),(3,2))

print(a);

[[0 1 2 0 1 2]
 [0 1 2 0 1 2]
 [0 1 2 0 1 2]]


In [44]:
a = np.tile(np.arange(3),(3,1))
print("a is ",a)

b = np.arange(3)

print("b is: ",b)

a+b

a is  [[0 1 2]
 [0 1 2]
 [0 1 2]]
b is:  [0 1 2]


array([[0, 2, 4],
       [0, 2, 4],
       [0, 2, 4]])

In [39]:
a = np.arange(4)

a.shape
print(a)

[0 1 2 3]


In [40]:
a = a[:, np.newaxis] #converts it to 2d array

a.shape

(4, 1)

In [41]:
print(a)

[[0]
 [1]
 [2]
 [3]]


In [46]:
b = np.array([0,1,2,3])

In [45]:
a+b

array([[0, 2, 4],
       [0, 2, 4],
       [0, 2, 4]])

In [ ]:
# Array Shape Manipulations
# Flattening

In [47]:
#Converts 2d array to 1d array

a = np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [48]:
print(a.ravel()); #converted to 1d array

[1 2 3 4 5 6]


In [49]:
print(a.T.ravel()); #transposed 1d array


[1 4 2 5 3 6]


In [ ]:
# Reshaping its opposite to flattening

In [50]:
a = np.array([[1,2,3],[4,5,6]])
print(a);
print(id(a))
print(a.shape);

[[1 2 3]
 [4 5 6]]
4568222176
(2, 3)


In [51]:
b = a.ravel();
print(b)
print(id(b))

[1 2 3 4 5 6]
4568222256


In [52]:
b=b.reshape(2,3);
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
# a,b are stored in same mem location

In [53]:
b[0,0]=10
a

array([[10,  2,  3],
       [ 4,  5,  6]])

In [54]:
a = np.arange(4*3*2).reshape(4,3,2);
a.shape

(4, 3, 2)

In [55]:
print(a);

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]


In [56]:
#arg1 -> indicates which matrix
#arg2, arg3 are i,j of that matrix
print(a[0,1,1])

3


In [57]:
a = np.arange(4);

a.resize((8,))

print(a)

[0 1 2 3 0 0 0 0]


In [ ]:
# Operators which are not present in Java

In [59]:
#Arithematic

print(16//10) #Floor Division

1


In [60]:
print(2**5) #power or exponent

32


In [61]:
a, b = True, False

print(a and b)

print(a or b)

print(not a)

False
True
False


In [62]:
# Special Operators

a = 5
b = 5

print(a is b) #checks if a,b memory locations are same

print(a is not b)


li = [1,2,3]
li2 = [1,2,3]

print(li is li2) #fals it doesnt work for lists

True
False
False


In [63]:
# MemberShip Operatos


li = [1,2,3]

print(1 in li)

print(10 not in li)

True
True
