In [ ]:
# NumPy Arrays
# Python Objects:
# 1) It Contains High level objects: Integer,floationg point

# 2) Containers: Lists, dictionaries internally build so that We can perform mathamatical operations extensively.

# NumPy Provides:
# 1) MultiDimension arrays support 
# 2) Closer to hardware(efficiency) 
# 3) Designed for Sci-fi computations 
# 4) Array oriented computing

In [1]:
import numpy as np

#this creates numpy array from list.
a= np.array([1,2,3]); 

#other way of creating np array
b=np.arange(10);

print(a);

print(b);

[1 2 3]
[0 1 2 3 4 5 6 7 8 9]


In [2]:
# Why is it useful: Memory Efficient container that provides fast numerical operations

#py lists

li = list(range(1000));

# %timeit here runs the below statement
# 1000 times and calculates the time 
# in terms of mean and std deviation in time
# and gives the time taken to run per loop

%timeit [i**2 for i in li]

314 µs ± 6.97 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [3]:
li = np.arange(1000);
%timeit np.array(i**2 for i in li)


2.53 µs ± 58.6 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [4]:
# 1-d Array

a = np.array([0,1,2,3,4]);

print(a);

print(type(a));

[0 1 2 3 4]
<class 'numpy.ndarray'>


In [5]:
# prints dimension

print(a.ndim);

1


In [6]:
# Shape

print(a.shape);

(5,)


In [7]:
print(len(a));

5


In [8]:
# 2-D Array

b = np.array([[1,2,3],[4,5,6]]);

print(b);

print("shape is ",b.shape);

print("Length here is no.of rows",len(b));

print("Dimension ",b.ndim);

[[1 2 3]
 [4 5 6]]
shape is  (2, 3)
Length here is no.of rows 2
Dimension  2


In [9]:
# 3-D Array or n-D Array or Tensor

c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

print(c);

print("shape is ",c.shape);

print("Length here is no.of rows",len(c));

print("Dimension ",c.ndim);

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
shape is  (2, 2, 2)
Length here is no.of rows 2
Dimension  3


In [10]:
# Creating np array using predefined Functions

#arange()

a = np.arange(10);

#start, end, step size
b = np.arange(1,8,2);

print(a,"\n",b);

[0 1 2 3 4 5 6 7 8 9] 
 [1 3 5 7]


In [11]:
# Dividing line into pieces

#start, end, no.of points on line
c = np.linspace(0,1,6)

print(c);

[0.  0.2 0.4 0.6 0.8 1. ]


In [12]:
# one matrix

#3x3 matrix
d = np.ones((3,3))

print(d);

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [13]:
# Zero Matrix

e = np.zeros((4,4));

print(e);

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [14]:
# Identity matrix

f = np.eye(3);

print(f);

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [15]:
f = np.eye(2,3);

print(f);

[[1. 0. 0.]
 [0. 1. 0.]]


In [16]:
g = np.diag([1,2,3,4]);

print(g);

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [17]:
print(np.diag(g));

[1 2 3 4]


In [18]:
# creating array of rand values

#uniform random number
h = np.random.rand(4);

print(h);

[0.56532227 0.59551581 0.49731892 0.93381409]


In [19]:
#gaussian random number
i = np.random.randn(4);

print(i);

[-0.16577899  1.3615818   0.57268795  0.05796318]


In [20]:
# Basic Datatypes

a = np.arange(10)

print(a.dtype);

int64


In [21]:
a = np.arange(10, dtype='float')

print(a.dtype);

print(a)

float64
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [22]:
d = np.array([1+2j,2+4j])

print(d.dtype);

complex128


In [23]:
# Index and Slicing¶

a = np.arange(6);

print(a[0]);

0


In [24]:
a = np.diag([1,2,3])

print(a[1][1]);

2


In [25]:
a[1,1]=10;

print(a);

[[ 1  0  0]
 [ 0 10  0]
 [ 0  0  3]]


In [26]:
# Slicing

a = np.arange(10);

print(a[1:6:2]);

[1 3 5]


In [27]:
print(a[2:])

[2 3 4 5 6 7 8 9]


In [28]:
print(a[0:2]);

[0 1]


In [29]:
print(a[:])

[0 1 2 3 4 5 6 7 8 9]


In [30]:
print(a[:3]);

[0 1 2]


In [31]:
print(a[::-1]); #reverse order

[9 8 7 6 5 4 3 2 1 0]


In [32]:
# Memory Sharing

a = np.arange(10);

print(a);

[0 1 2 3 4 5 6 7 8 9]


In [33]:
b = a[::2];

print(b);


[0 2 4 6 8]


In [34]:
print(np.shares_memory(a,b));

True


In [ ]:
# Observation: Both a and b share same memory i.e b is subset of a it access the elements form a's memory location, internally a view is created from that b will access the values of a.

In [35]:
b[0]=77;

print(b);

print(a);

[77  2  4  6  8]
[77  1  2  3  4  5  6  7  8  9]


In [ ]:
# Obeseravtion: if we modify 'b', 'a' is also modified because they share memory i.e they are in same location.

In [36]:
# Indexing with an array of integers

a = np.arange(0,100,10);

print(a);

#list of indices, i.e values at this indices
# will be present in the list
print(a[[2,3,2,4,2,5]]);

[ 0 10 20 30 40 50 60 70 80 90]
[20 30 20 40 20 50]


In [37]:
#value at indices 0,3 will be replaced by 77
a[[0,3]]=77;

print(a);

[77 10 20 77 40 50 60 70 80 90]
